package com.chazal.fdj.league

import com.chazal.fdj.shared.data.league.model.LeagueResponse
import com.chazal.fdj.shared.data.league.model.TeamResponse
import com.chazal.fdj.league.domain.model.LeagueItemBlockUI
import com.chazal.fdj.league.domain.model.LeagueUI
import com.chazal.fdj.league.presentation.LeagueScreenState

internal val dummyTeamResponseSuccess: List<TeamResponse> = listOf(
    TeamResponse(
        idTeam = "idTest",
        idSoccerXML = "",
        idAPIfootball = "",
        intLoved = "",
        strTeam = "",
        strTeamShort = "",
        strAlternative = "",
        intFormedYear = "",
        strSport = "",
        strLeague = "",
        idLeague = "",
        strLeague2 = "",
        idLeague2 = "",
        strLeague3 = "",
        idLeague3 = "",
        strLeague4 = "",
        idLeague4 = "",
        strLeague5 = "",
        idLeague5 = "",
        strLeague6 = "",
        idLeague6 = "",
        strLeague7 = "",
        idLeague7 = "",
        strDivision = "",
        strStadium = "",
        strKeywords = "",
        strRSS = "",
        strStadiumThumb = "",
        strStadiumDescription = "",
        strStadiumLocation = "",
        strStadiumCapacity = "",
        strWebsite = "",
        strFacebook = "",
        strTwitter = "",
        strDescriptionEN = "",
        strDescriptionDE = "",
        strDescriptionFR = "aaa",
        strDescriptionCN = "",
        strDescriptionIT = "",
        strDescriptionJP = "",
        strDescriptionRU = "",
        strDescriptionES = "",
        strDescriptionPT = "",
        strDescriptionSE = "",
        strDescriptionNL = "",
        strDescriptionHU = "",
        strDescriptionNO = "",
        strDescriptionIL = "",
        strDescriptionPL = "",
        strKitColor1 = "",
        strKitColor2 = "",
        strKitColor3 = "",
        strGender = "",
        strCountry = "",
        strTeamBadge = "",
        strTeamJersey = "",
        strLogo = "logo",
        strTeamFanart1 = "",
        strTeamFanart2 = "",
        strTeamFanart3 = "",
        strTeamFanart4 = "",
        strTeamBanner = "",
        strYoutube = "",
        strLocked = "",
    ),
    TeamResponse(
        idTeam = "idTest",
        idSoccerXML = "",
        idAPIfootball = "",
        intLoved = "",
        strTeam = "",
        strTeamShort = "",
        strAlternative = "",
        intFormedYear = "",
        strSport = "",
        strLeague = "",
        idLeague = "",
        strLeague2 = "",
        idLeague2 = "",
        strLeague3 = "",
        idLeague3 = "",
        strLeague4 = "",
        idLeague4 = "",
        strLeague5 = "",
        idLeague5 = "",
        strLeague6 = "",
        idLeague6 = "",
        strLeague7 = "",
        idLeague7 = "",
        strDivision = "",
        strStadium = "",
        strKeywords = "",
        strRSS = "",
        strStadiumThumb = "",
        strStadiumDescription = "",
        strStadiumLocation = "",
        strStadiumCapacity = "",
        strWebsite = "",
        strFacebook = "",
        strTwitter = "",
        strDescriptionEN = "",
        strDescriptionDE = "",
        strDescriptionFR = "aab",
        strDescriptionCN = "",
        strDescriptionIT = "",
        strDescriptionJP = "",
        strDescriptionRU = "",
        strDescriptionES = "",
        strDescriptionPT = "",
        strDescriptionSE = "",
        strDescriptionNL = "",
        strDescriptionHU = "",
        strDescriptionNO = "",
        strDescriptionIL = "",
        strDescriptionPL = "",
        strKitColor1 = "",
        strKitColor2 = "",
        strKitColor3 = "",
        strGender = "",
        strCountry = "",
        strTeamBadge = "",
        strTeamJersey = "",
        strLogo = "lolo",
        strTeamFanart1 = "",
        strTeamFanart2 = "",
        strTeamFanart3 = "",
        strTeamFanart4 = "",
        strTeamBanner = "",
        strYoutube = "",
        strLocked = "",
    ),
    TeamResponse(
        idTeam = "idTest",
        idSoccerXML = "",
        idAPIfootball = "",
        intLoved = "",
        strTeam = "",
        strTeamShort = "",
        strAlternative = "",
        intFormedYear = "",
        strSport = "",
        strLeague = "",
        idLeague = "",
        strLeague2 = "",
        idLeague2 = "",
        strLeague3 = "",
        idLeague3 = "",
        strLeague4 = "",
        idLeague4 = "",
        strLeague5 = "",
        idLeague5 = "",
        strLeague6 = "",
        idLeague6 = "",
        strLeague7 = "",
        idLeague7 = "",
        strDivision = "",
        strStadium = "",
        strKeywords = "",
        strRSS = "",
        strStadiumThumb = "",
        strStadiumDescription = "",
        strStadiumLocation = "",
        strStadiumCapacity = "",
        strWebsite = "",
        strFacebook = "",
        strTwitter = "",
        strDescriptionEN = "",
        strDescriptionDE = "",
        strDescriptionFR = "aac",
        strDescriptionCN = "",
        strDescriptionIT = "",
        strDescriptionJP = "",
        strDescriptionRU = "",
        strDescriptionES = "",
        strDescriptionPT = "",
        strDescriptionSE = "",
        strDescriptionNL = "",
        strDescriptionHU = "",
        strDescriptionNO = "",
        strDescriptionIL = "",
        strDescriptionPL = "",
        strKitColor1 = "",
        strKitColor2 = "",
        strKitColor3 = "",
        strGender = "",
        strCountry = "",
        strTeamBadge = "",
        strTeamJersey = "",
        strLogo = "gogo",
        strTeamFanart1 = "",
        strTeamFanart2 = "",
        strTeamFanart3 = "",
        strTeamFanart4 = "",
        strTeamBanner = "",
        strYoutube = "",
        strLocked = "",
    ),
    TeamResponse(
        idTeam = "idTest",
        idSoccerXML = "",
        idAPIfootball = "",
        intLoved = "",
        strTeam = "",
        strTeamShort = "",
        strAlternative = "",
        intFormedYear = "",
        strSport = "",
        strLeague = "",
        idLeague = "",
        strLeague2 = "",
        idLeague2 = "",
        strLeague3 = "",
        idLeague3 = "",
        strLeague4 = "",
        idLeague4 = "",
        strLeague5 = "",
        idLeague5 = "",
        strLeague6 = "",
        idLeague6 = "",
        strLeague7 = "",
        idLeague7 = "",
        strDivision = "",
        strStadium = "",
        strKeywords = "",
        strRSS = "",
        strStadiumThumb = "",
        strStadiumDescription = "",
        strStadiumLocation = "",
        strStadiumCapacity = "",
        strWebsite = "",
        strFacebook = "",
        strTwitter = "",
        strDescriptionEN = "",
        strDescriptionDE = "",
        strDescriptionFR = "aad",
        strDescriptionCN = "",
        strDescriptionIT = "",
        strDescriptionJP = "",
        strDescriptionRU = "",
        strDescriptionES = "",
        strDescriptionPT = "",
        strDescriptionSE = "",
        strDescriptionNL = "",
        strDescriptionHU = "",
        strDescriptionNO = "",
        strDescriptionIL = "",
        strDescriptionPL = "",
        strKitColor1 = "",
        strKitColor2 = "",
        strKitColor3 = "",
        strGender = "",
        strCountry = "",
        strTeamBadge = "",
        strTeamJersey = "",
        strLogo = "adada",
        strTeamFanart1 = "",
        strTeamFanart2 = "",
        strTeamFanart3 = "",
        strTeamFanart4 = "",
        strTeamBanner = "",
        strYoutube = "",
        strLocked = "",
    )
)

internal val dummyLeagueResponseSuccess: LeagueResponse = LeagueResponse(
    teams = dummyTeamResponseSuccess
)

internal val dummyLeagueResponse = LeagueUI(
    listOf(
        LeagueItemBlockUI(
            logoUrl = "adada",
            description = "aad"
        ),
        LeagueItemBlockUI(
            logoUrl = "lolo",
            description = "aab"
        )
    )
)

internal val dummySuccessState = LeagueScreenState.Success(
    LeagueUI(
        listOf(
            LeagueItemBlockUI(
                logoUrl = "adada",
                description = "aad"
            ),
            LeagueItemBlockUI(
                logoUrl = "lolo",
                description = "aab"
            )
        )
    )
)